---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: url-service
      db: brev
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: url-service-password
      roles:
        - name: clusterAdmin
          db: brev
        - name: userAdminAnyDatabase
          db: brev
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                limits:
                  memory: 150M
                requests:
                  memory: 100M
            - name: mongodb-agent
              resources:
                limits:
                  memory: 150M
                requests:
                  memory: 100M
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100M
            selector:
              matchLabels:
                # We set this labels when creating the volume
                # (see below)
                type: data
            storageClassName: default
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100M
            selector:
              matchLabels:
                type: logs
            storageClassName: default

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: url-service-password
type: Opaque
stringData:
  password: "<your-password-here>"