---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mdb
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: url-service
      db: brev
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: url-service-password
      roles:
        - name: clusterAdmin
          db: brev
        - name: userAdminAnyDatabase
          db: brev
      scramCredentialsSecretName: vg1e-ulv5
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:

        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                limits:
                  memory: 150M
                requests:
                  memory: 100M
            - name: mongodb-agent
              resources:
                limits:
                  memory: 150M
                requests:
                  memory: 100M
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
            selector:
              matchLabels:
                # We set this labels when creating the volume
                # (see pv.yaml)
                type: data
            storageClassName: hostpath
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
            selector:
              matchLabels:
                type: logs
            storageClassName: hostpath