apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clickhouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: clickhouse
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_DB
            - name: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_USER
          image: clickhouse/clickhouse-server
          name: clickhouse
          ports:
            - containerPort: 8123
              hostPort: 8123
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: clickhouse-claim0
      restartPolicy: Always
      volumes:
        - name: clickhouse-claim0
          persistentVolumeClaim:
            claimName: clickhouse-claim0
status: {}
