---
# Here we create 2 PVs
# (one for data, one for logs)
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: data
  name: data-volume-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp/data/mongo-data-0
#    type: ""
#  storageClassName: hostpath
#  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: logs
  name: logs-volume-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp/data/mongo-logs-0
#    type: ""
  persistentVolumeReclaimPolicy: Retain
#  storageClassName: manual
#  volumeMode: Filesystem