apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-cluster"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: clickhouse-pvc
      podTemplate: clickhouse:23.3

  configuration:
    users:
      analytics/default: secret
      analytics/password: password
      analytics/profile: default
      analytics/quota: default
      analytics/networks/ip: "::/0"
    zookeeper:
      nodes:
        - host: zookeeper.default.svc.cluster.local
    clusters:
      - name: "default"
        layout:
          shardsCount: 1
          replicasCount: 1

  templates:
    volumeClaimTemplates:
      - name: clickhouse-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
    podTemplates:
      - name: clickhouse:23.3
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.3